consul-server:
  build: .
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8600:8600/udp"
  environment:
    - CONSUL_SERVER=true
      #- CONSUL_CLUSTER_TAG_KEY=component
      #- CONSUL_CLUSTER_TAG_VALUE=consul-server
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
