consul-server:
  build: .
  net: "host"
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8600:8600/udp"
  environment:
    - CONSUL_AUTODISCOVER=true
    ##- CONSUL_JOIN_SERVERS=["10.0.0.227"]
    - CONSUL_SERVER=true
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
